import requests
import json
from typing import Optional
from datetime import datetime
from config.config import Config

class SlackService:
    """Slack 服务类 - 支持 Block Kit 和简单文本格式"""
    
    def __init__(self, config: Config):
        self.config = config
    
    def send_message(self, content: str, prefix: str = "AI分析报告") -> bool:
        """
        发送分析报告到Slack（支持Block Kit和简单文本两种格式）
        
        Args:
            content: 要发送的消息内容
            prefix: 消息前缀
            
        Returns:
            发送成功返回True，否则返回False
        """
        try:
            current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            
            if self.config.use_slack_blocks:
                # 使用 Slack Block Kit 格式（更美观）
                slack_data = {
                    "blocks": [
                        {
                            "type": "header",
                            "text": {
                                "type": "plain_text",
                                "text": f"🤖 {prefix}"
                            }
                        },
                        {
                            "type": "section",
                            "fields": [
                                {
                                    "type": "mrkdwn",
                                    "text": f"*📅 Generated Time:*\n{current_time}"
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": f"*🔍 Query Content:*\n{self.config.default_query}"
                                }
                            ]
                        },
                        {
                            "type": "divider"
                        },
                        {
                            "type": "section",
                            "text": {
                                "type": "mrkdwn",
                                "text": f"*📊 Analysis Result:*\n{content}"
                            }
                        },
                        {
                            "type": "divider"
                        },
                        {
                            "type": "context",
                            "elements": [
                                {
                                    "type": "mrkdwn",
                                    "text": "_This report is automatically generated by BochaAI Search + DeepSeek Analysis_"
                                }
                            ]
                        }
                    ]
                }
            else:
                # 使用简单文本格式（兼容性更好）
                slack_message = f"""🤖 {prefix}

📅 Generated Time: {current_time}
🔍 Query Content: {self.config.default_query}

📊 Analysis Result:
{content}

───────────────────────────
This report is automatically generated by BochaAI Search + DeepSeek Analysis"""
                
                slack_data = {
                    'text': slack_message
                }
            
            print("📱 Sending message to Slack...")
            response = requests.post(
                self.config.slack_webhook_url,
                data=json.dumps(slack_data),
                headers={'Content-Type': 'application/json'}
            )
            
            if response.status_code == 200:
                print("✅ Message sent to Slack successfully!")
                return True
            else:
                print(f"❌ Slack request failed, status code: {response.status_code}")
                print(response.text)
                return False
                
        except Exception as e:
            print(f"❌ Slack service error: {str(e)}")
            return False
    
    def send_error_message(self, error_msg: str) -> bool:
        """发送错误消息到Slack"""
        return self.send_message(error_msg, "Error Report") 