version: "1.0"
description: "统一的财经新闻分析任务配置"

# 全局配置
global:
  slack_webhook_url: "https://hooks.slack.com/services/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"
  use_slack_blocks: false
  agent_type: "financial"

# 定时任务列表
tasks:
  - id: "daily_news"
    name: "每日美股财经新闻总结"
    query: "总结昨天的美股金融财经新闻"
    schedule: "0 8 * * *"  # 每天北京时间8点（早上8点）
    freshness: "day"
    count: 50
    enabled: true
    analysis_prompt: "请总结和分析以下美股财经新闻，重点关注市场动态、重要公司公告、政策影响等关键信息。请用中文输出。"
    
  - id: "macro_factors"
    name: "美股宏观经济因素分析"
    query: "当前影响美股市场的宏观经济因素分析"
    schedule: "5 8 * * *"  # 每天北京时间8点05分（错开避免冲突）
    freshness: "day"
    count: 50
    enabled: true
    analysis_prompt: "请从宏观经济角度分析以下信息，重点关注对美股市场的影响，包括利率、通胀、GDP、就业数据、政策变化等关键因素。请用中文输出。"
    
  - id: "weekly_outlook"
    name: "每周美股风险与机会分析"
    query: "未来一周美股市场风险与机会分析 财报季 经济数据 政策预期"
    schedule: "0 8 * * 1"  # 每周一北京时间8点（早上8点）
    freshness: "day"
    count: 50
    enabled: true
    analysis_prompt: "请分析未来一周美股市场的风险与机会，重点关注即将发布的经济数据、企业财报、政策事件等，提供投资策略建议。请用中文输出。" 